### ISSUE TITLE
Forward default notification system

### ISSUE THREAD

**Issue by goranmoomin** [zzzeyez/xanthia#2]
As I am using [pecan](https://github.com/zzzeyez/pecan), I would like to use xanthia for my notifications; but I am not sure how to make current notifications to xanthia.

Is there no way to forward the default macOS notification system to xanthia?

**Comment by zzzeyez** [comment]
i am not aware of a way.  i do however know how to do the reverse with `terminal-notifier` (in case ubersicht is not running)

**Comment by goranmoomin** [comment]
@zzzeyez Okay... thanks for clarifying!
